export const slot = [
  "slot.weapon.mainhand",
  "slot.weapon.offhand",
  "slot.armor.head",
  "slot.armor.chest",
  "slot.armor.legs",
  "slot.armor.feet",
  "slot.armor.body",
  "slot.hotbar",
  "slot.inventory",
  "slot.enderchest",
  "slot.saddle",
  "slot.armor",
  "slot.chest",
  "slot.equippable",
];
